#!/usr/bin/env python3

from threading import Thread
from random import shuffle, randint
import time
import subprocess
import os

class img_changer():
	def __init__(self, wait=30):
		self.files = self.get_files()
		self.wait = wait
		self.runloop = True

	def set_background(self):
		#com = f"sudo gsettings get org.gnome.desktop.background picture-uri \"file://{filepath}\""
		#com = f"sudo gsettings set org.gnome.desktop.background picture-uri \"file:///{filepath}\""
		filepath = self.get_img()
		com = f"gsettings set org.gnome.desktop.background picture-uri \"file:///{filepath}\""
		ret = subprocess.check_output(com, shell=True)
	def get_img(self):
		shuffle(self.files)
		shuffle(self.files)
		shuffle(self.files)
		return self.files[randint(0, len(self.files) - 1)]
	def get_files(self, path='/home/monkey/Pictures/Wallpapers'):
		com = f"find \"{path}\" -name \"*.*\""
		try:
			files = subprocess.check_output(com, shell=True).decode().strip().split("\n")
		except Exception as e:
			files = []
		return files
	def run(self):
		self.t = Thread(target=self.loop)
		self.t.setDaemon(True)
		self.t.start()
	def loop(self):
		while self.runloop:
			self.set_background()
			time.sleep(self.wait)
		exit()

if __name__ == "__main__":
	c = img_changer()
	c.loop()
